version: '3.8'

services:
  mariadb:
    image: mariadb:10.11.2-jammy
    restart: always
    volumes:
      - mariadb:/var/lib/mysql:z
    environment:
      MYSQL_DATABASE: poweruptime
      MYSQL_USER: poweruptime
      MYSQL_PASSWORD: poweruptime
      MYSQL_ROOT_PASSWORD: poweruptime
    networks:
      - network
    ports:
      - '3326:3306'

  redis:
    image: redis:7.0.10-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/data
    networks:
      - network
    ports:
      - '3327:6379'

volumes:
  redis:
  mariadb:

networks:
  network:
